- name: Install nvm
  include_role:
    name: pablocrivella.nvm
  vars:
    nvm_env: user
    nvm_version: v0.33.0
    nvm_default_node_version: stable
    nvm_node_versions:
      - stable
      - 4.2
    nvm_global_packages:  ['babel-cli', 'babel-preset-es2016', 'babel-preset-es2015', 'babel-preset-env', 'babel-preset-react', 'grunt', 'gulp', 'typescript', 'angular-cli', 'bower', 'npm-check-updates', 'yo']


- name: Babel - generate BableRc file if needed
  file: state=touch path={{home_directory}}/.babelrc


- name: Babel - Save default presets in BabelRc
  shell: echo "{\"presets\":[\"env\",\"es2015\"]}" >> {{home_directory}}/.babelrc

- name: NodeJs Source bash_profile
  shell: source {{home_directory}}/.bashrc
