- name: Check for homebrew
  stat: path=/usr/local/Cellar
  register: brew_installed

- name: Install homebrew if needed
  shell: >
    ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  when: brew_installed.stat.exists == false

- name: Update homebrew
  homebrew: update_homebrew=yes

- name: Ensure presence of bash_profile
  file: state=touch path={{ ansible_env.HOME}}/.bash_profile

- name: Load bashrc in bash_profile
  lineinfile: dest={{ ansible_env.HOME}}/.bash_profile regexp="\. \$HOME\/\.bashrc" line="[[ -r $HOME/.bashrc ]] && . $HOME/.bashrc"

- name: Ensure presence of bashrc
  file: state=touch path={{ ansible_env.HOME}}/.bashrc

- name: Add local bin to $PATH
  shell: echo "export PATH=\"$HOME/local/bin\:\$PATH\"" >> {{ ansible_env.HOME}}/.bashrc

- name: Add brew to beginning of $PATH
  shell: echo "export PATH=\"/usr/local/bin\:\$PATH\"" >> {{ ansible_env.HOME}}/.bashrc

- name: Set bash_aliases
  template:
    src: bash_aliases.j2
    dest: "{{ ansible_env.HOME}}/.bash_aliases"

- name: Tap homebrew cask
  homebrew_tap: name=caskroom/cask state=present

- name: Install homebrew cask
  homebrew: name="brew-cask" state=latest

- name: Clean homebrew cask
  shell: brew cask cleanup
  
- name: Common utilities
  homebrew: name={{ item }} state=present
  tags:
    - utils
  with_items:
    - git
    - curl
    - build-essential
    - libssl-dev
    - htop   # [A better top](http://hisham.hm/htop/)
    - git-flow
    - hub    # Command line interface for GitHub (wrapper for `git`)
    - tree   # I love this util for printing a tree of directories
    - httpie # Improved web service testing
    - imagemagick # Convert all the things
    - python3
    - awscli
    - s3cmd
    - trash  # Move to trash from the command line
    - qlcolorcode 
    - qlstephen 
    - qlmarkdown 
    - quicklook-json 
    - qlprettypatch 
    - quicklook-csv 
    - betterzipql 
    - qlimagesize 
    - webpquicklook 
    - suspicious-package 
    - qlvideo

- name: GNU global with ctags & pygments
  shell: brew install global --with-ctags --with-pygments

#- name: Install pure (simple and sleak prompt)
#  npm: name=pure-prompt global=yes

- name: Tap homebrew fonts
  homebrew_tap: tap=caskroom/fonts state=present

- name: Install fonts
  homebrew_cask: name={{ item }} state=present
  with_items:
    - font-fira-code


- name: Setup default git configuraiton
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "{{ person.name }}" }
    - {name: "user.email", value: "{{ person.email }}" }
    - {name: "ui.color",   value: "True" }