#!/usr/bin/env ANSIBLE_HOSTS="localhost," ANSIBLE_CONNECTION=local ansible-playbook
# vim:ft=yaml
---
- name: install com.apple.dock defaults - com.apple.dock
  osx_defaults:
    domain: com.apple.dock
    state: present
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "orientation", type: "string", value: "left" }
    - { key: "autohide", type: "bool", value: "true" }

    - { key: "mouse-over-hilite-stack", type: "bool", value: "true" }
    - { key: "tilesize", type: "int", value: "1" }
    - { key: "mineffect", type: "string", value: "scale" }
    - { key: "launchanim", type: "bool", value: "false" }
    - { key: "expose-animation-duration", type: "float", value: "0.1" }
