#!/usr/bin/env ANSIBLE_HOSTS="localhost," ANSIBLE_CONNECTION=local ansible-playbook
# vim:ft=yaml
---
- name: com.apple.driver.AppleBluetoothMultitouch.trackpad
  osx_defaults:
      domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
      state: present
      key: "{{ item.key }}"
      type: "{{ item.type }}"
      value: "{{ item.value }}"
  with_items:
  - { key: "TrackpadPinch", type: "int", value: "0" }
  - { key: "Clicking", type: "bool", value: "true" }


- name: Trackpad: enable tap to click for this user and for the login screen (1/2)
  command: defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

- name: Trackpad: enable tap to click for this user and for the login screen (2/2)
  command: defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1


- name: Trackpad: Disable press-and-hold for keys in favor of key repeat
  command: defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false