- name: Disable Resume system-wide
  command: defaults write NSGlobalDomain NSQuitAlwaysKeepsWindows -bool false

- name: Enable full keyboard access for all controls
  command: defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

- name: Save to disk (not to iCloud) by default
  command: defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

- name: Disable smart quotes as they’re annoying when typing code
  command: defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

- name: Disable smart dashes as they’re annoying when typing code
  command: defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

- name: Disable auto-correct
  command: defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

- name: Set Control+scrolling to zoom in
  command: defaults write com.apple.universalaccess {{ item.key }} {{ item.value }}
  with_items:
    - {key: 'closeViewScrollWheelToggle', value: '-bool true'}
    - {key: 'HIDScrollZoomModifierMask', value: '-int 262144'}


- name: Avoid creating .DS_Store files on network volumes
  command: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true